apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app/rollout.yaml
- app/service-v2.yaml
- app/ingress.yaml
- app/service-v1.yaml
images:
- name: alexmt/rollouts-demo #Tomado app demo del dockerhub de Alexmt 
  newTag: red
